/**
 * FusionCharts: Flash Player detection and Chart embedding.
 * Version 1.2.3F ( 22 November 2008) - Specialized for FusionChartsFREE 
 * 					Checking Flash Version >=6 and added updateChartXML() for FREE Charts.
 * Version: 1.2.3 (1st September, 2008) - Added Fix for % and & characters, scaled dimensions, fixes in to properly handling of double quotes and single quotes in setDataXML() function.
 * Version: 1.2.2 (10th July, 2008) - Added Fix for % scaled dimensions, fixes in setDataXML() and setDataURL() functions
 * Version: 1.2.1 (21st December, 2007) - Added setting up Transparent/opaque mode: setTransparent() function 
 * Version: 1.2 (1st November, 2007) - Added FORM fixes for IE 
 * Version: 1.1 (29th June, 2007) - Added Player detection, New conditional fixes for IE
 *
 * Morphed from SWFObject (http://blog.deconcept.com/swfobject/) under MIT License:
 * http://www.opensource.org/licenses/mit-license.php
 *
 */
 if("undefined"==typeof infosoftglobal)var infosoftglobal={};"undefined"==typeof infosoftglobal.FusionChartsUtil&&(infosoftglobal.FusionChartsUtil={});
infosoftglobal.FusionCharts=function(a,b,c,d,e,f,g,h,j,k,l){document.getElementById&&(this.initialDataSet=!1,this.params={},this.variables={},this.attributes=[],a&&this.setAttribute("swf",a),b&&this.setAttribute("id",b),(c=c.toString().replace(/\%$/,"%25"))&&this.setAttribute("width",c),(d=d.toString().replace(/\%$/,"%25"))&&this.setAttribute("height",d),g&&this.addParam("bgcolor",g),this.addParam("quality","high"),this.addParam("allowScriptAccess","always"),this.addVariable("chartWidth",c),this.addVariable("chartHeight",
d),this.addVariable("debugMode",e?e:0),this.addVariable("DOMId",b),this.addVariable("registerWithJS",f?f:0),this.addVariable("scaleMode",h?h:"noScale"),this.addVariable("lang",j?j:"EN"),this.detectFlashVersion=k?k:1,this.autoInstallRedirect=l?l:1,this.installedVer=infosoftglobal.FusionChartsUtil.getPlayerVersion(),!window.opera&&(document.all&&7<this.installedVer.major)&&(infosoftglobal.FusionCharts.doPrepUnload=!0))};
infosoftglobal.FusionCharts.prototype={setAttribute:function(a,b){this.attributes[a]=b},getAttribute:function(a){return this.attributes[a]},addParam:function(a,b){this.params[a]=b},getParams:function(){return this.params},addVariable:function(a,b){this.variables[a]=b},getVariable:function(a){return this.variables[a]},getVariables:function(){return this.variables},getVariablePairs:function(){var a=[],b,c=this.getVariables();for(b in c)a.push(b+"="+c[b]);return a},getSWFHTML:function(){var a="";if(navigator.plugins&&
navigator.mimeTypes&&navigator.mimeTypes.length){var a='<embed type="application/x-shockwave-flash" src="'+this.getAttribute("swf")+'" width="'+this.getAttribute("width")+'" height="'+this.getAttribute("height")+'"  ',a=a+(' id="'+this.getAttribute("id")+'" name="'+this.getAttribute("id")+'" '),b=this.getParams(),c;for(c in b)a+=[c]+'="'+b[c]+'" ';b=this.getVariablePairs().join("&");0<b.length&&(a+='flashvars="'+b+'"');a+="/>"}else{a='<object id="'+this.getAttribute("id")+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="'+
this.getAttribute("width")+'" height="'+this.getAttribute("height")+'">';a+='<param name="movie" value="'+this.getAttribute("swf")+'" />';b=this.getParams();for(c in b)a+='<param name="'+c+'" value="'+b[c]+'" />';b=this.getVariablePairs().join("&");0<b.length&&(a+='<param name="flashvars" value="'+b+'" />');a+="</object>"}return a},setDataURL:function(a){if(!1==this.initialDataSet)this.addVariable("dataURL",a),this.initialDataSet=!0;else{var b=infosoftglobal.FusionChartsUtil.getChartObject(this.getAttribute("id"));
b.setDataURL||__flash__addCallback(b,"setDataURL");b.setDataURL(a)}},encodeDataXML:function(a){var b=a.match(/=\s*\".*?\"/g);if(b)for(var c=0;c<b.length;c++){var d=b[c].replace(/^=\s*\"|\"$/g,""),d=d.replace(/\'/g,"%26apos;"),e=a.indexOf(b[c]),d="='"+d+"'",f=a.substring(0,e);a=a.substring(e+b[c].length);a=f+d+a}a=a.replace(/\"/g,"%26quot;");a=a.replace(/%(?![\da-f]{2}|[\da-f]{4})/ig,"%25");return a=a.replace(/\&/g,"%26")},setDataXML:function(a){!1==this.initialDataSet?(this.addVariable("dataXML",
this.encodeDataXML(a)),this.initialDataSet=!0):infosoftglobal.FusionChartsUtil.getChartObject(this.getAttribute("id")).setDataXML(a)},setTransparent:function(a){"undefined"==typeof a&&(a=!0);a?this.addParam("WMode","transparent"):this.addParam("WMode","Opaque")},render:function(a){if(1==this.detectFlashVersion&&6>this.installedVer.major)if(1==this.autoInstallRedirect)if(window.confirm("You need Adobe Flash Player 6 (or above) to view the charts. It is a free and lightweight installation from Adobe.com. Please click on Ok to install the same."))window.location=
"http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash";else return!1;else return!1;else return("string"==typeof a?document.getElementById(a):a).innerHTML=this.getSWFHTML(),!document.embeds[this.getAttribute("id")]&&!window[this.getAttribute("id")]&&(window[this.getAttribute("id")]=document.getElementById(this.getAttribute("id"))),!0}};
infosoftglobal.FusionChartsUtil.getPlayerVersion=function(){var a=new infosoftglobal.PlayerVersion([0,0,0]);if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=new infosoftglobal.PlayerVersion(b.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s+r|\s+b[0-9]+)/,".").split(".")))}else if(navigator.userAgent&&0<=navigator.userAgent.indexOf("Windows CE"))for(var b=1,c=3;b;)try{c++,b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+c),
a=new infosoftglobal.PlayerVersion([c,0,0])}catch(d){b=null}else{try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(e){try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),a=new infosoftglobal.PlayerVersion([6,0,21]),b.AllowScriptAccess="always"}catch(f){if(6==a.major)return a}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(g){}}null!=b&&(a=new infosoftglobal.PlayerVersion(b.GetVariable("$version").split(" ")[1].split(",")))}return a};
infosoftglobal.PlayerVersion=function(a){this.major=null!=a[0]?parseInt(a[0]):0;this.minor=null!=a[1]?parseInt(a[1]):0;this.rev=null!=a[2]?parseInt(a[2]):0};infosoftglobal.FusionChartsUtil.cleanupSWFs=function(){for(var a=document.getElementsByTagName("OBJECT"),b=a.length-1;0<=b;b--){a[b].style.display="none";for(var c in a[b])"function"==typeof a[b][c]&&(a[b][c]=function(){})}};
infosoftglobal.FusionCharts.doPrepUnload&&!infosoftglobal.unloadSet&&(infosoftglobal.FusionChartsUtil.prepUnload=function(){__flash_unloadHandler=function(){};__flash_savedUnloadHandler=function(){};window.attachEvent("onunload",infosoftglobal.FusionChartsUtil.cleanupSWFs)},window.attachEvent("onbeforeunload",infosoftglobal.FusionChartsUtil.prepUnload),infosoftglobal.unloadSet=!0);!document.getElementById&&document.all&&(document.getElementById=function(a){return document.all[a]});
null==Array.prototype.push&&(Array.prototype.push=function(a){this[this.length]=a;return this.length});infosoftglobal.FusionChartsUtil.getChartObject=function(a){var b=null;(b=-1==navigator.appName.indexOf("Microsoft Internet")?document.embeds&&document.embeds[a]?document.embeds[a]:window.document[a]:window[a])||(b=document.getElementById(a));return b};
infosoftglobal.FusionChartsUtil.updateChartXML=function(a,b){var c=infosoftglobal.FusionChartsUtil.getChartObject(a);c.SetVariable("_root.dataURL","");c.SetVariable("_root.isNewData","1");c.SetVariable("_root.newData",b);c.TGotoLabel("/","JavaScriptHandler")};var getChartFromId=infosoftglobal.FusionChartsUtil.getChartObject,updateChartXML=infosoftglobal.FusionChartsUtil.updateChartXML,FusionCharts=infosoftglobal.FusionCharts;