/*
 * jQuery UI Menubar @VERSION
 *
 * Copyright 2011, AUTHORS.txt (http://jqueryui.com/about)
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * http://docs.jquery.com/UI/Menubar
 *
 * Depends:
 *	jquery.ui.core.js
 *	jquery.ui.widget.js
 *	jquery.ui.position.js
 *	jquery.ui.menu.js
 */
 (function(c){c.widget("ui.menubar",{version:"@VERSION",options:{autoExpand:!1,buttons:!1,items:"li",menuElement:"ul",menuIcon:!1,position:{my:"left top",at:"left bottom"}},_create:function(){var b=this;this.menuItems=this.element.children(this.options.items);this.items=this.menuItems.children("button, a");this.menuItems.addClass("ui-menubar-item").attr("role","presentation");this.items.slice(1).attr("tabIndex",-1);this.element.addClass("ui-menubar ui-widget-header ui-helper-clearfix").attr("role",
"menubar");this._focusable(this.items);this._hoverable(this.items);this.items.siblings(this.options.menuElement).menu({position:{within:this.options.position.within},select:function(a,d){d.item.parents("ul.ui-menu:last").hide();b._close();c(a.target).prev().focus();b._trigger("select",a,d)},menus:b.options.menuElement}).hide().attr({"aria-hidden":"true","aria-expanded":"false"}).bind("keydown.menubar",function(a){if(!c(this).is(":hidden"))switch(a.keyCode){case c.ui.keyCode.LEFT:b.previous(a);a.preventDefault();
break;case c.ui.keyCode.RIGHT:b.next(a),a.preventDefault()}});this.items.each(function(){var a=c(this),d=a.next(b.options.menuElement);d.length?(a.bind("click.menubar focus.menubar mouseenter.menubar",function(a){if("focus"!==a.type||a.originalEvent)if(a.preventDefault(),"click"===a.type&&d.is(":visible")&&b.active&&b.active[0]===d[0])b._close();else if(b.open&&"mouseenter"===a.type||"click"===a.type||b.options.autoExpand)b.options.autoExpand&&clearTimeout(b.closeTimer),b._open(a,d)}).bind("keydown",
function(a){switch(a.keyCode){case c.ui.keyCode.SPACE:case c.ui.keyCode.UP:case c.ui.keyCode.DOWN:b._open(a,c(this).next());a.preventDefault();break;case c.ui.keyCode.LEFT:b.previous(a);a.preventDefault();break;case c.ui.keyCode.RIGHT:b.next(a),a.preventDefault()}}).attr("aria-haspopup","true"),b.options.menuIcon&&(a.addClass("ui-state-default").append("<span class='ui-button-icon-secondary ui-icon ui-icon-triangle-1-s'></span>"),a.removeClass("ui-button-text-only").addClass("ui-button-text-icon-secondary"))):
a.bind("click.menubar mouseenter.menubar",function(a){(b.open&&"mouseenter"===a.type||"click"===a.type)&&b._close()});a.addClass("ui-button ui-widget ui-button-text-only ui-menubar-link").attr("role","menuitem").wrapInner("<span class='ui-button-text'></span>");b.options.buttons&&a.removeClass("ui-menubar-link").addClass("ui-state-default")});b._on({keydown:function(a){if(a.keyCode===c.ui.keyCode.ESCAPE&&b.active&&!0!==b.active.menu("collapse",a)){var d=b.active;b.active.blur();b._close(a);d.prev().focus()}},
focusin:function(){clearTimeout(b.closeTimer)},focusout:function(a){b.closeTimer=setTimeout(function(){b._close(a)},150)},"mouseleave .ui-menubar-item":function(a){b.options.autoExpand&&(b.closeTimer=setTimeout(function(){b._close(a)},150))},"mouseenter .ui-menubar-item":function(){clearTimeout(b.closeTimer)}});this.openSubmenus=0},_destroy:function(){this.menuItems.removeClass("ui-menubar-item").removeAttr("role");this.element.removeClass("ui-menubar ui-widget-header ui-helper-clearfix").removeAttr("role").unbind(".menubar");
this.items.unbind(".menubar").removeClass("ui-button ui-widget ui-button-text-only ui-menubar-link ui-state-default").removeAttr("role").removeAttr("aria-haspopup").children("span.ui-button-text").each(function(){var b=c(this);b.parent().html(b.html())}).end().children(".ui-icon").remove();this.element.find(":ui-menu").menu("destroy").show().removeAttr("aria-hidden").removeAttr("aria-expanded").removeAttr("tabindex").unbind(".menubar")},_close:function(){this.active&&this.active.length&&(this.active.menu("collapseAll").hide().attr({"aria-hidden":"true",
"aria-expanded":"false"}),this.active.prev().removeClass("ui-state-active").removeAttr("tabIndex"),this.active=null,this.open=!1,this.openSubmenus=0)},_open:function(b,a){this.active&&this.active[0]===a[0]||(this.active&&(this.active.menu("collapseAll").hide().attr({"aria-hidden":"true","aria-expanded":"false"}),this.active.prev().removeClass("ui-state-active")),a.prev().addClass("ui-state-active").attr("tabIndex",-1),this.active=a.show().removeAttr("aria-hidden").attr("aria-expanded","true").menu("focus",
b,a.children(".ui-menu-item").first()).focus().focusin(),this.open=!0)},next:function(b){this.open&&this.active.data("menu").active.has(".ui-menu").length?this.openSubmenus++:(this.openSubmenus=0,this._move("next","first",b))},previous:function(b){this.open&&this.openSubmenus?this.openSubmenus--:(this.openSubmenus=0,this._move("prev","last",b))},_move:function(b,a,d){this.active.closest(".ui-menubar-item");debugger;this.open?(b=[b+"All"](this.options.items).first().children(".ui-menu").eq(0),a=this.menuItems[a]().children(".ui-menu").eq(0)):
d?(b=c(d.target).closest(".ui-menubar-item")[b+"All"](this.options.items).children(".ui-menubar-link").eq(0),a=this.menuItems[a]().children(".ui-menubar-link").eq(0)):b=a=this.menuItems.children("a").eq(0);b.length?this.open?this._open(d,b):b.removeAttr("tabIndex")[0].focus():this.open?this._open(d,a):a.removeAttr("tabIndex")[0].focus()}})})(jQuery);
